apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  name: hacbs-test-project-3s72
spec:
  selector: {}
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-unio-tenant/rhtap-demo-app/hacbs-test-project-3s72@sha256:5ff9eba10e21ae8b5776183cffc8fd12f1f49de32ce8449da0aaac47d18de1cb
        name: hacbs-jvm-build-test-project
        resources: {}
status: {}
