apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    app.kubernetes.io/created-by: application-service
    app.kubernetes.io/instance: hacbs-test-project-3s72
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: hacbs-test-project-3s72
    app.kubernetes.io/part-of: rhtap-demo-app
  name: hacbs-test-project-3s72
spec:
  replicas: 1
  revisionHistoryLimit: 0
  selector:
    matchLabels:
      app: hacbs-jvm-build-test-project
      app.kubernetes.io/instance: hacbs-test-project-3s72
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: hacbs-jvm-build-test-project
        app.kubernetes.io/instance: hacbs-test-project-3s72
    spec:
      containers:
      - image: quay.io/redhat-appstudio-qe/rhtap-demo-unio-tenant/rhtap-demo-app/hacbs-test-project-3s72@sha256:f502efd478e19c9f2af3fcc589141f1d5424a0fb3083938332463c9514da8294
        name: hacbs-jvm-build-test-project
        ports:
        - containerPort: 8081
          name: http
          protocol: TCP
        resources:
          limits:
            cpu: 500m
            memory: 1Gi
status: {}
